# Generated by Django 3.2.2 on 2021-07-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0008_alter_room_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='send_by',
        ),
    ]
