# Generated by Django 3.2.2 on 2021-07-15 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0011_alter_messages_message_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='message_created_by',
        ),
    ]
